import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:flutter_widgets/bloc/bloc.dart';
// import 'package:flutter_widgets/main.dart';
import 'package:flutter_widgets/services/services.dart';
import 'package:fluttertoast/fluttertoast.dart';
part "main_page.dart";
part "home_page.dart";
part "sign_in.dart";
part "sign_up.dart";
part "mainmenu.dart";
part "add_page.dart";
part "data_page.dart";
part "account_page.dart";
